#!/bin/sh
for x in `ls *.eps`
 do
  if [ ! -f $x ]; then
   continue
  fi
   `sed -e 's/Mesuree/Mesur\ée/' $x > temp`
   mv temp $x
 done
for x in `ls *.eps`
 do
  if [ ! -f $x ]; then
   continue
  fi
   `sed -e 's/Defaut/Standard/' $x > temp`
   mv temp $x
 done
for x in `ls *.eps`
 do
  if [ ! -f $x ]; then
   continue
  fi
   `sed -e 's/Prediction/Pr\édiction/' $x > temp`
   mv temp $x
 done
